title = "alobogiron"

[params.author]
name = "AndrÃ© Giron"
image = "img/author.jpg"
email = "giron@labnet.nce.ufrj.br"
headline = "ğŸ¢ This site is still in producing ğŸ¢"
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer fringilla consequat velit id viverra. Aliquam lobortis, arcu et semper tincidunt, mi augue tincidunt libero, ut pellentesque nibh arcu nec enim. Sed eu commodo ipsum. Integer bibendum finibus tellus, sed bibendum ipsum bibendum vel. Ut eget malesuada turpis."
links = [
    { email = "giron@labnet.nce.ufrj.br" },
    { github = "https://github.com/alobogiron" },
    { linkedin = "https://www.linkedin.com/in/alobogiron/" },
]