title = "alobogiron"
copyright = "All content licensed [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)ğŸ§"

[params.author]
name = "AndrÃ© Giron"
image = "img/author.jpg"
email = "giron@labnet.nce.ufrj.br"
headline = "An aspiring engineer writing about his experiments ğŸ¢"
bio = "Research, try, learn and do it again!"
links = [
    { email = "giron@labnet.nce.ufrj.br" },
    { github = "https://github.com/alobogiron" },
    { linkedin = "https://www.linkedin.com/in/alobogiron/" },
]
